name: dev

on:
  push:
    branches: [ "dev" ]
    paths:
     - 'src/**'
     - 'cake/**'
     - '.github/**'
  pull_request:
    branches: [ "dev" ]
    paths:
     - 'src/**'
     - 'cake/**'
     - '.github/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: [self-hosted]  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'   
        
    - name: "Get github nuget source"
      #uses: simatic-ax/actions/setup-apax-runner@main
      run:  dotnet nuget add source --username PTKu --password ${{ secrets.GH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ix-ax/index.json"
                 
    - name: "login to apax"  
      run: apax login -p ${{ secrets.APAX_TOKEN }}      
        
    - name: "Build  script"  
      run: dotnet build cake/Build.csproj
                       
    - name: "Run build script"
      run: dotnet run --project cake/Build.csproj --do-test true --do-pack true --test-level 1      

